//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stok.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Satis
    {
        public int satisId { get; set; }
        public Nullable<int> urun { get; set; }
        public Nullable<int> musteri { get; set; }
        public Nullable<byte> adet { get; set; }
        public Nullable<decimal> fiyat { get; set; }
    
        public virtual Tbl_Musteriler Tbl_Musteriler { get; set; }
        public virtual tbl_Urunler tbl_Urunler { get; set; }
    }
}
